name: Code Tests

on: push

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Code Formatting (App)
        run: |
          pip install .
          pip install pytest
          pwd
          python3 -m pytest tests -s
